### ISSUE TITLE
Package name manifest

### ISSUE THREAD

**Issue by gambogo** [DexPatcher/dexpatcher-gradle-tools#1]
Hi Lanchon

I tried patching app without set package name identifier in manifest file or set the real package name identifier then the compiler show error. But when i set any package name, compiling successful.

Because i need to sign in app with google account so i think the package name must be original.
Can we remain the original package name for the app ?

Thank you so much

**Comment by gambogo** [comment]
i repost my question in this branch

**Comment by Lanchon** [comment]
yes, you absolutely can keep the APP ID of the original app in the patched app. in fact, my sample called 'patched-app' does exactly that.

in android, you cannot compose different android libraries that use the same PACKAGE ATTRIBUTE. each one has to have its own 'R' and other generated classes, and those go in the package named in the PACKAGE ATTRIBUTE, so those attributes must be different.

an android app can have several, not just one, binary components and their PACKAGE ATTRIBUTES, but ONLY ONE APPI ID.

in the sample 'patched-app':
-the original app id is: makeinfo.com.getid.apk
-thus, the package of the apk-library is also: makeinfo.com.getid.apk
-the package of the hack is: [hack.getid](https://github.com/Lanchon/DexPatcher-gradle-samples/blob/master/patched-app/patched/src/main/AndroidManifest.xml#L1)
-but we select the hacked app id to match the original id: [makeinfo.com.getid.apk](https://github.com/Lanchon/DexPatcher-gradle-samples/blob/master/patched-app/patched/build.gradle#L42)

is this way:
-all parts of the app have different PACKAGE ATTRIBUTE
-but the APP ID of the rebuilt app matches the original

what is visible form the outside (to android, play store, etc) is ONLY THE APP ID.

**Comment by Lanchon** [comment]
please reopen if needed

**Comment by gambogo** [comment]
now i know the patched example still use original APP ID and the hack.getid just like the library (i think so). But i cannot install overwrite to current app from App Store, when i removed the original app and install released apk is successful.

And other issues are some google services not working like Push Notification, Sign In google account. is there any inject code that break the google service ?

**Comment by Lanchon** [comment]
no. nothing breaks anything.

if the app id is the same, then the store is not accepting the app because it is signed with a different key. the other symptoms (google services not working) are also indicative of this.

**Comment by gambogo** [comment]
seem like there has no way to use google service because of different key.

i am very appriciated your help.
Thank you so much

**Comment by Lanchon** [comment]
you CANNOT forge a signature!!!
not without a quantum computer anyway.

you either need to:
-sign with the same key
-or publish under different APP ID
